import React, { useState } from 'react';
import { post, media } from './api';
import { Button, Empty, Icon } from './ui';
export function Sessions({ state, refresh, notify, compact = false, onViewAll }) {
  const [filter,setFilter] = useState('all'), [selected,setSelected] = useState(null), [printing,setPrinting] = useState(false);
  const jobs = (compact ? state.jobs.slice(0,6) : state.jobs).filter(j => filter === 'all' || j.status === filter);
  const job = state.jobs.find(j => j.id === selected);
  async function action(id,name) {
    if (name === 'delete' && !window.confirm('Delete this session and its photo files? Its download link will stop working.')) return;
    if (name === 'retry' && !window.confirm('Retry this generation? A previous timed-out request may already have been charged.')) return;
    try { if (name === 'print') setPrinting(true); const response=await post(`/api/sessions/${id}/${name}`); await refresh(); if (name === 'print') notify(response.queued ? 'Print queued for the Windows booth.' : 'Photo sent to the Windows print queue.'); if (name === 'delete') setSelected(null); }
    catch(e) { notify(e.message,true); } finally { setPrinting(false); }
  }
  return <section className={`sessions ${compact ? 'compact' : ''}`}>
    <div className="section-heading"><h2>{compact ? 'Recent sessions' : 'Sessions'}</h2>{compact ? <button className="text-button" onClick={onViewAll}>View all <Icon name="chevron" size={17}/></button> : <Button secondary onClick={async () => { try { await post('/api/queue',{ paused:!state.paused }); await refresh(); } catch(e) { notify(e.message,true); } }}>{state.paused ? 'Resume queue' : 'Pause queue'}</Button>}</div>
    {!compact ? <div className="filters" role="group" aria-label="Session filters">{['all','captured','queued','generating','complete','failed'].map(f => <button key={f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)}>{f === 'complete' ? 'Ready' : f[0].toUpperCase()+f.slice(1)}</button>)}<span>{state.paused ? 'Queue paused. Current generation can finish.' : 'New results appear on the display automatically.'}</span></div> : null}
    {!jobs.length ? <Empty>{compact ? 'Your completed portraits will appear here.' : 'No sessions to show yet.'}</Empty> : <div className="session-grid">{jobs.map(j => <button className="session-card" key={j.id} onClick={() => setSelected(j.id)}><img src={media(j,true)} alt="Guest session preview" loading="lazy"/><div><strong>{j.status === 'complete' ? 'Ready to print' : j.status}</strong><small>{new Date(j.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{j.mode === 'rehearsal' ? ' · Rehearsal' : ''}</small></div></button>)}</div>}
    {job ? <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="session-modal" role="dialog" aria-modal="true" aria-label="Session details" onClick={e => e.stopPropagation()}><button className="close-button" aria-label="Close session details" onClick={() => setSelected(null)}>×</button><img className="modal-photo" src={media(job)} alt="Guest portrait"/><div className="modal-details"><h2>{job.status === 'complete' ? 'Ready to keep.' : 'Your session'}</h2><p>{job.mode === 'rehearsal' ? 'Rehearsal · No AI was applied.' : 'AI golf portrait'}</p>{job.error ? <p className="inline-error">{job.error}</p> : null}{job.status === 'complete' ? <><Button disabled={printing} onClick={() => action(job.id,'print')}><Icon name="print"/>{printing ? 'Sending…' : 'Print photo'}</Button><a className="button secondary" href={media(job)} download="golf-portrait.jpg">Save photo</a>{job.downloadUrl ? <><img className="qr" src={`/api/qr/${job.id}`} alt="Download QR code"/><a className="download-link" href={job.downloadUrl} target="_blank" rel="noreferrer">Open download page</a><small>{state.cloud ? 'Guests can download using mobile data or Wi-Fi.' : state.config.downloadBaseUrl ? 'Using your configured download address.' : 'Guest must use the booth’s Wi-Fi.'}</small></> : <p>No network address is available for QR downloads.</p>}</> : null}{['captured','failed'].includes(job.status) ? <Button onClick={() => action(job.id,job.status === 'failed' ? 'retry' : 'generate')}>{job.status === 'failed' ? 'Retry generation' : 'Generate portrait'}</Button> : null}<button className="text-button danger" disabled={job.status === 'generating'} onClick={() => action(job.id,'delete')}>Delete session</button></div></section></div> : null}
  </section>;
}
