import React, { useEffect, useState } from 'react';
import { api, post } from './api';
import { Button, Field, Icon } from './ui';
import { imageModels, qualityOptions, sizeOptions } from '../shared/image-models.mjs';
export function Setup({ state, refresh, notify, returnToKiosk = false }) {
  const [form,setForm] = useState({ ...state.config }), [key,setKey] = useState(''), [printers,setPrinters] = useState([]), [saving,setSaving] = useState(false);
  const change = (name,value) => setForm(p => ({...p,[name]:value}));
  const changeModel = model => setForm(p => ({...p, model,
    quality: qualityOptions(model).includes(p.quality) ? p.quality : 'high',
    size: sizeOptions(model).includes(p.size) ? p.size : '1024x1536',
  }));
  useEffect(() => { api('/api/printers').then(setPrinters).catch(() => {}); },[]);
  async function save() { setSaving(true); try { await post('/api/settings',form); await refresh(); if (returnToKiosk) location.assign('/kiosk'); else notify('Settings saved.'); } catch(e) { notify(e.message,true); } finally { setSaving(false); } }
  async function asset(e,kind) { const file=e.target.files?.[0]; if(!file) return; try { await api('/api/'+kind,{method:'POST',body:file}); await refresh(); notify(({reference:'Golf reference saved.','outfit-reference':'Outfit reference saved.',overlay:'Branding overlay saved.'})[kind]); } catch(e) { notify(e.message,true); } e.target.value=''; }
  async function removeOutfitReference() { try { await api('/api/outfit-reference',{method:'DELETE'}); await refresh(); notify('Outfit reference removed.'); } catch(e) { notify(e.message,true); } }
  return <div className="setup"><div className="section-heading"><div><h1>Make it your event.</h1><p className="lead">{returnToKiosk ? 'Choose your camera and printer, then save to start the event.' : 'Camera, creative direction and delivery.'}</p></div><Button disabled={saving} onClick={save}>{saving ? 'Saving…' : returnToKiosk ? 'Save & return to welcome' : 'Save settings'}</Button></div>
    <div className="setup-grid"><section><h2>Camera</h2><Field label="Capture connection"><select value={form.cameraMode} onChange={e => change('cameraMode',e.target.value)}><option value="canon">Canon USB · direct capture</option><option value="folder">EOS Utility · camera folder</option><option value="webcam">Webcam · development testing</option></select></Field>
      {form.cameraMode === 'canon' ? <><Field label="Canon SDK folder" hint="Folder containing the licensed 64-bit EDSDK.dll and its dependencies. Not included in this build."><input value={form.sdkPath} onChange={e => change('sdkPath',e.target.value)} placeholder="C:\CanonSDK\EDSDK\Dll"/></Field><p className="help">R100 / EOS 200D: connect USB, choose JPEG capture, and close EOS Utility before direct capture. This build has no Canon live preview; it shows the full-resolution photo after capture. Hardware validation is still required.</p></> : null}
      {form.cameraMode === 'folder' ? <><Field label="Canon download folder" hint="Set the same folder in EOS Utility. New JPEGs only; existing files are ignored."><input value={form.watchFolder} onChange={e => change('watchFolder',e.target.value)} placeholder="C:\BoothCaptures"/></Field><label className="check-row"><input type="checkbox" checked={form.watchEnabled} onChange={e => change('watchEnabled',e.target.checked)}/>Monitor new camera photos</label><p className="help">Use the shutter in EOS Utility or on the camera. Capture photo arms the screen; folder mode cannot release the shutter. Monitoring must be enabled again after restarting.</p></> : null}
      <label className="check-row"><input type="checkbox" checked={form.autoGenerate} onChange={e => change('autoGenerate',e.target.checked)}/>Generate automatically after capture</label>
      <h2>AI connection</h2><Field label="OpenAI API key" hint={state.hasKey ? 'A key is saved. Leave this blank to keep it. Stored with Windows user encryption.' : 'Enter the key here, never in chat. API billing is separate from ChatGPT.'}><input autoComplete="off" type="password" value={key} onChange={e => setKey(e.target.value)} placeholder={state.hasKey ? 'Key saved securely' : 'Your API key'}/></Field><Button secondary disabled={!key.trim()} onClick={async () => {try {await post('/api/key',{key:key.trim()});setKey('');await refresh();notify('API key saved securely.');} catch(e){notify(e.message,true);} }}>Save API key</Button>
      <Field label="Generation mode"><select value={form.mode} onChange={e => change('mode',e.target.value)}><option value="rehearsal">Rehearsal · no AI, no API charges</option><option value="live">Live AI · paid generations</option></select></Field><p className="help">Rehearsal frames the original photo to test capture, printing and display. It does not create a golf scene.</p>
      <Field label="Image model"><select value={form.model} onChange={e => changeModel(e.target.value)}>{imageModels.map(m => <option key={m}>{m}</option>)}</select></Field><Field label="Quality" hint="Max prioritizes detail and can take longer and cost more per photo."><select value={form.quality} onChange={e => change('quality',e.target.value)}>{qualityOptions(form.model).map(q => <option key={q} value={q}>{({max:'Max',xhigh:'Extra high',high:'High',medium:'Medium',low:'Low'})[q]}</option>)}</select></Field>
      <Field label="AI image size" hint="The finished print remains 1200 × 1800. A larger AI portrait provides more detail before framing."><select value={form.size} onChange={e => change('size',e.target.value)}>{sizeOptions(form.model).map(s => <option key={s} value={s}>{s.replace('x',' × ')}{s === '1536x2304' ? ' · Detailed portrait' : ''}</option>)}</select></Field>
    </section><section><h2>Reference & branding</h2><Field label="Event name"><input value={form.eventName} onChange={e => change('eventName',e.target.value)} maxLength={80}/></Field><div className="reference-setting"><img src={`/api/media/assets/${state.config.reference}?thumb=1`} alt="Saved golf reference"/><div><strong>Your saved golf reference</strong><p>The guest’s captured photo supplies their identity. This reference supplies the setting and pose.</p><label className="file-button">Change reference<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => asset(e,'reference')}/></label></div></div>
      <div className="reference-setting">{state.config.outfitReference ? <img src={`/api/media/assets/${state.config.outfitReference}?thumb=1`} alt="Saved women's golf outfit reference"/> : null}<div><strong>Women’s golf outfit reference</strong><p>{state.config.outfitReference ? 'Both outfit examples accompany each guest photo. Clothing fit adapts to the guest’s appearance; their own face, hairstyle and proportions stay the guide.' : 'Optional second example for a tailored polo, trousers and light belt. Add it to guide clothing fit alongside the main golf reference.'}</p><div className="reference-actions"><label className="file-button">{state.config.outfitReference ? 'Change outfit reference' : 'Add outfit reference'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => asset(e,'outfit-reference')}/></label>{state.config.outfitReference ? <button className="text-button" onClick={removeOutfitReference}>Remove outfit reference</button> : null}</div></div></div>
      <Field label="Generation prompt"><textarea rows={8} value={form.prompt} onChange={e => change('prompt',e.target.value)}/></Field>
      <label className="check-row"><input type="checkbox" checked={form.frameEnabled} onChange={e => change('frameEnabled',e.target.checked)}/>Add the red event frame</label><Field label="Frame colour"><input type="color" value={form.frameColor} onChange={e => change('frameColor',e.target.value)}/></Field><Field label="Placeholder event title"><input value={form.footerTitle} onChange={e => change('footerTitle',e.target.value)} maxLength={36}/></Field><Field label="Footer subtitle"><input value={form.footerSubtitle} onChange={e => change('footerSubtitle',e.target.value)} maxLength={64}/></Field><Field label="Final branding overlay" hint="Optional transparent PNG, 1200 × 1800. Applied after AI, so your artwork stays consistent."><input type="file" accept="image/png" onChange={e => asset(e,'overlay')}/></Field>{state.config.overlay ? <button className="text-button" onClick={async()=>{await api('/api/overlay',{method:'DELETE'});await refresh();notify('Overlay removed.');}}>Remove saved overlay</button> : null}
    </section><section><h2>Printer & display</h2><Field label="Windows printer" hint="Install the printer’s Windows driver and select 4×6-inch portrait paper in its preferences."><select value={form.printerName} onChange={e => change('printerName',e.target.value)}><option value="">Choose printer</option>{printers.map(p => <option key={p}>{p}</option>)}</select></Field><p className="help">Each Print photo action sends one copy. The image is fitted within the printer’s printable area. Borderless printing depends on the driver.</p><Field label="Seconds per image on the large screen"><input type="number" min="5" max="120" value={form.displaySeconds} onChange={e=>change('displaySeconds',Number(e.target.value))}/></Field><a className="button secondary" href="/display" target="_blank" rel="noreferrer"><Icon name="external"/>Open display</a><a className="button secondary" href="/kiosk" target="_blank" rel="noreferrer">Open guest capture screen</a>
      <h2>Downloads & storage</h2><Field label="Download address" hint="Leave blank for the booth’s local Wi-Fi address. For mobile-data downloads, configure a public HTTPS address that forwards only guest port 4311."><input type="url" value={form.downloadBaseUrl} placeholder={state.addresses[0] ? `http://${state.addresses[0]}:${state.publicPort}` : 'https://photos.your-event.com'} onChange={e=>change('downloadBaseUrl',e.target.value)}/></Field><p className="help">Local QR links require the same Wi-Fi, a running booth PC, and network access to port {state.publicPort}. Printing needs no QR connection. The app does not publish an internet address automatically.</p><Field label="Keep photos for this many days" hint="Expired photos are deleted while the app is running or when it next starts."><input type="number" min="1" max="90" value={form.retentionDays} onChange={e=>change('retentionDays',Number(e.target.value))}/></Field><Button secondary onClick={async()=>{if(window.confirm('Stop the booth and its download service?')){await post('/api/shutdown');notify('Booth stopped. Close this window.');}}}>Stop booth</Button>
    </section></div>
  </div>;
}
