import React, { useEffect, useRef, useState } from 'react';
import { Button, Field, Icon } from './ui';
import { FullscreenButton } from './FullscreenButton';
import { connectHelper, connected, disconnectHelper, getPresets, helperJson, helperOrigin, isLocal } from './temporary-api';
import { imageModels, qualityOptions, sizeOptions } from '../shared/image-models.mjs';
export function TemporarySettings({state,save,back,setAssets}){
  const [config,setConfig]=useState(state.config),[equipment,setEquipment]=useState(state.equipment||{sdkPath:'',printerName:''}),[printers,setPrinters]=useState([]),[key,setKey]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connectionUrl,setConnectionUrl]=useState('');
  const pairing=useRef(null);
  useEffect(()=>()=>pairing.current?.abort(),[]);
  const update=(name,value)=>setConfig(c=>({...c,[name]:value}));
  async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}}
  async function connect(){const popup=window.open('about:blank','fairway-helper-connect');await run(async()=>{pairing.current=new AbortController();const info=await connectHelper(popup,setConnectionUrl,pairing.current.signal);const presets=await getPresets(info);setAssets(a=>({...presets,...a}));setConnectionUrl('');setMessage('Windows helper connected for this booth browser.');});}
  return <><header className="app-header"><a className="brand" href="/kiosk" onClick={e=>{e.preventDefault();back();}}><Icon name="flag" size={30}/>Fairway Studio</a><div className="operator-screen-links"><Button secondary onClick={back}>Back to welcome</Button><a className="button secondary" href="/display" target="_blank" rel="noreferrer">Open display</a><FullscreenButton/></div></header><main className="temporary-settings">
    <div className="temporary-settings-heading"><span className="eyebrow">BEFORE THE FIRST GUEST</span><h1>Set up your booth.</h1><p>Capture → Review → Generate → Print → Clear.<br/>Guest photos stay in memory and disappear when you refresh.</p></div>
    <div className="temporary-settings-grid"><section className="temporary-card"><h2><Icon name="camera"/>Camera & printer</h2>
      <Field label="Camera"><select value={config.cameraMode} onChange={e=>update('cameraMode',e.target.value)}><option value="canon">Canon USB · R100 / EOS 200D</option><option value="webcam">Browser camera / webcam</option></select></Field>
      {isLocal?<><Field label="Canon SDK folder" hint="The folder containing your licensed 64-bit EDSDK.dll. Close EOS Utility before capture."><input value={equipment.sdkPath} onChange={e=>setEquipment(s=>({...s,sdkPath:e.target.value}))} placeholder="C:\Canon\EDSDK\Dll"/></Field><Field label="Windows printer"><input list="temporary-printers" value={equipment.printerName} onChange={e=>setEquipment(s=>({...s,printerName:e.target.value}))} placeholder="Choose your photo printer"/><datalist id="temporary-printers">{printers.map(p=><option key={p} value={p}/>)}</datalist></Field><Button secondary disabled={busy} onClick={()=>run(async()=>{const p=await helperJson('/api/temporary/printers');setPrinters(p.printers);setMessage(p.printers.length?'Printers loaded. Choose a printer above.':'No Windows printers were found. Install the printer driver first.');})}>Find Windows printers</Button><p className="temporary-hint">Set the printer driver to 4 × 6 inch portrait paper. The photo clears when Windows accepts the print job.</p></>:<><p className="temporary-hint">For Canon capture, direct printing and live AI, run the Windows helper on this PC and connect it here. The connection is created automatically; no password or device token to enter.</p><Button disabled={busy} onClick={connect}>{busy?'Connecting…':'Connect Windows helper'}</Button>{connectionUrl?<p className="temporary-hint">Choose Allow in the helper window. <a href={connectionUrl} target="_blank" rel="noreferrer">Open connection request</a></p>:null}{connected()?<><a className="button secondary" href={helperOrigin+'/?view=setup'} target="_blank" rel="noreferrer">Open camera & printer settings</a><Button secondary onClick={()=>{disconnectHelper();setMessage('Helper disconnected.');}}>Disconnect helper</Button></>:null}<p className="temporary-hint">Without the helper, Rehearsal can use your browser camera and print dialog. After printing, select Done & clear photo.</p></>}
    </section><section className="temporary-card"><h2><Icon name="plug"/>AI generation</h2><Field label="Generation mode"><select value={config.mode} onChange={e=>update('mode',e.target.value)}><option value="rehearsal">Rehearsal · No AI charge</option><option value="live">Live AI · Paid generation</option></select></Field><Field label="Image model"><select value={config.model} onChange={e=>{const model=e.target.value;setConfig(c=>({...c,model,quality:qualityOptions(model)[0],size:sizeOptions(model)[0]}));}}>{imageModels.map(m=><option key={m}>{m}</option>)}</select></Field><div className="temporary-field-row"><Field label="Quality"><select value={config.quality} onChange={e=>update('quality',e.target.value)}>{qualityOptions(config.model).map(q=><option key={q}>{q}</option>)}</select></Field><Field label="Image size"><select value={config.size} onChange={e=>update('size',e.target.value)}>{sizeOptions(config.model).map(s=><option key={s}>{s}</option>)}</select></Field></div>
      {isLocal?<><Field label="OpenAI API key" hint={state.hasKey?'An API key is configured. Enter a replacement to change it.':'Saved with Windows user encryption, never sent to guest screens.'}><input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Enter your API key"/></Field><Button secondary disabled={busy||!key.trim()} onClick={()=>run(async()=>{await helperJson('/api/temporary/key',{key:key.trim()});setKey('');setMessage('API key saved. Use the same key in Vercel.');})}>Save API key</Button></>:<p className="temporary-hint">Set <strong>OPENAI_API_KEY</strong> in Vercel, and save the same key in Windows helper Setup. It is the only deployment value you need to add. {state.hasKey?'The server has an API key.':'The server has no API key yet.'}</p>}
      <p className="temporary-hint">There are no automatic retries. Refresh discards the photo, but an AI request already sent may still be charged. Vercel generation must finish within its function time limit.</p>
    </section><section className="temporary-card temporary-wide"><h2><Icon name="image"/>Golf scene & event design</h2><Field label="Event name"><input maxLength={80} value={config.eventName} onChange={e=>update('eventName',e.target.value)}/></Field><Field label="Custom AI prompt"><textarea rows={7} maxLength={12000} value={config.prompt} onChange={e=>update('prompt',e.target.value)}/></Field><div className="temporary-asset-grid">{[['reference','Golf reference','Bundled golf scene used by default.'],['outfitReference','Additional outfit reference','Optional clothing and pose guide.'],['overlay','Branding overlay','Optional transparent PNG under 1 MB.']].map(([name,label,hint])=><div key={name}><Field label={label} hint={hint}><input type="file" accept={name==='overlay'?'image/png':'image/jpeg,image/png,image/webp'} onChange={e=>setAssets(a=>({...a,[name]:e.target.files[0]||null}))}/></Field>{state.assets[name]?<small>{state.assets[name].name} · temporary <button className="temporary-text-button" onClick={()=>setAssets(a=>({...a,[name]:null}))}>Remove</button></small>:null}</div>)}</div><p className="temporary-hint">These are event design references, not guest uploads. Selected reference files stay only until this page is refreshed. No guest upload option is shown.</p><label className="temporary-check"><input type="checkbox" checked={config.frameEnabled} onChange={e=>update('frameEnabled',e.target.checked)}/>Add the print frame</label><div className="temporary-field-row"><Field label="Frame colour"><input type="color" value={config.frameColor} onChange={e=>update('frameColor',e.target.value)}/></Field><Field label="Footer title"><input maxLength={36} value={config.footerTitle} onChange={e=>update('footerTitle',e.target.value)}/></Field><Field label="Footer subtitle"><input maxLength={64} value={config.footerSubtitle} onChange={e=>update('footerSubtitle',e.target.value)}/></Field></div>
    </section></div><div className="temporary-save"><Button disabled={busy} onClick={()=>run(async()=>{await save(config,equipment);setMessage('Settings saved. Your booth is ready.');})}>{busy?'Please wait…':'Save settings'}</Button><Button secondary disabled={busy} onClick={back}>Return to welcome</Button></div>{message||error?<p className={'temporary-message '+(error?'error':'')} role={error?'alert':'status'}>{error||message}</p>:null}
  </main></>;
}
