import React, {useEffect,useState} from 'react';
import {api,post} from './api';
import {Button,Field,Icon} from './ui';
import {CloudConnection} from './CloudAccess';
import {FullscreenButton} from './FullscreenButton';
export function WindowsHelper({state,refresh,notify}) {
  const [form,setForm]=useState({...state.config}),[printers,setPrinters]=useState([]),[busy,setBusy]=useState(false);
  const change=(name,value)=>setForm(p=>({...p,[name]:value}));
  useEffect(()=>{api('/api/printers').then(setPrinters).catch(e=>notify(e.message,true));},[notify]);
  const saveCamera=()=>post('/api/settings',{cameraMode:form.cameraMode,sdkPath:form.sdkPath,watchFolder:form.watchFolder,watchEnabled:form.watchEnabled,printerName:form.printerName,mode:'rehearsal',autoGenerate:false});
  async function save(){setBusy(true);try{await saveCamera();await refresh();notify('Camera and printer settings saved.');}catch(e){notify(e.message,true);}finally{setBusy(false);}}
  return <><header className="app-header"><span className="brand"><Icon name="flag" size={30}/>Fairway Cloud Helper</span><div className="operator-screen-links">{state.cloudConnection?.url ? <a className="button secondary" href={state.cloudConnection.url+'/kiosk'} target="_blank" rel="noreferrer">Open cloud booth</a> : null}<FullscreenButton/></div></header><main className="app-main"><div className="section-heading"><div><h1>Connect your event equipment.</h1><p className="lead">This PC handles the camera and printer. Your website handles the AI portraits.</p></div></div><div className="setup-grid helper-grid"><section><h2>Camera on this PC</h2><Field label="Camera connection"><select value={form.cameraMode} onChange={e=>change('cameraMode',e.target.value)}><option value="canon">Canon USB · direct capture</option><option value="folder">EOS Utility · camera folder</option></select></Field>
    {form.cameraMode==='canon' ? <><Field label="Canon SDK folder" hint="Folder containing your licensed 64-bit EDSDK.dll."><input value={form.sdkPath} onChange={e=>change('sdkPath',e.target.value)} placeholder="C:\CanonSDK\EDSDK\Dll"/></Field><p className="help">Connect the R100 / EOS 200D by USB, select JPEG capture, and close EOS Utility. This version shows the photo after capture.</p></> : <><Field label="EOS Utility download folder"><input value={form.watchFolder} onChange={e=>change('watchFolder',e.target.value)} placeholder="C:\BoothCaptures"/></Field><label className="check-row"><input type="checkbox" checked={form.watchEnabled} onChange={e=>change('watchEnabled',e.target.checked)}/>Monitor new JPEG photos</label><p className="help">Take the photo using EOS Utility or the camera shutter. Enable monitoring again after restarting the helper.</p></>}
    <h2>Printer on this PC</h2><Field label="Windows printer" hint="Set the printer driver to 4×6-inch portrait paper."><select value={form.printerName} onChange={e=>change('printerName',e.target.value)}><option value="">Choose printer</option>{printers.map(p=><option key={p}>{p}</option>)}</select></Field><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save camera & printer'}</Button></section><CloudConnection state={state} refresh={refresh} notify={notify} beforeConnect={saveCamera}/></div><p className="help">Keep this helper running during the event. Add the OpenAI key, reference images and branding on your Vercel website.</p>{state.watchError?<p className="inline-error" role="alert">{state.watchError}</p>:null}</main></>;
}
